name: Create Jira Ticket on Commit

on:
  push:
    branches: [ master ]  # Adjust branch(es) to trigger workflow
  pull_request:
    branches: [master]

jobs:
  create-jira-ticket:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create JIRA ticket
        env:
          JIRA_API_TOKEN: ${{ secrets.MYJIRATOKEN }}
        run: |
          # Define JIRA API endpoint
$url = "https://rkppersonal.atlassian.net/rest/api/3/issue/"

# Define project key, summary, description, and issue type
$projectKey = "NEW"
$summary = "Example Ticket"
$description = "This is an example JIRA ticket created via PowerShell"
$issueType = "Task"

# Encode API token
$base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("rkppersonal" + ":" + "MYJIRATOKEN")))

# Construct request body
$body = @{
    fields = @{
        project = @{
            key = $projectKey
        }
        summary = $summary
        description = $description
        issuetype = @{
            name = $issueType
        }
    }
} | ConvertTo-Json

$headers = @{
    "Authorization" = "Basic rkppersonal:MYJIRATOKEN"
    "Content-Type" = "application/json"
}

# Send request to create JIRA ticket
$response = Invoke-WebRequest -Uri $url -Method Post -Headers $headers -Body $body

# Output response content
Write-Output $response.Content

