name: Create JIRA Ticket

on:
  push:
    branches: [ master ]  # Adjust branch(es) to trigger workflow
  pull_request:
    branches: [master]

jobs:
  create-jira-ticket:
    name: Create JIRA Ticket
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PowerShell
        uses: azure/powershell@v1

      - name: Run PowerShell script to create JIRA ticket
        run: |
          $url = "https://rkppersonal.atlassian.net/rest/api/3/issue/"
          $projectKey = "NEW"
          $summary = "Example Ticket"
          $description = "This is an example JIRA ticket created via PowerShell"
          $issueType = "Task"
          $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("rkppersonal" + ":" + "${{ secrets.JIRA_API_TOKEN }}")))
          $body = @{
              fields = @{
                  project = @{
                      key = $projectKey
                  }
                  summary = $summary
                  description = $description
                  issuetype = @{
                      name = $issueType
                  }
              }
          } | ConvertTo-Json
          $headers = @{
              "Authorization" = "Basic $base64AuthInfo"
              "Content-Type" = "application/json"
          }
          $response = Invoke-WebRequest -Uri $url -Method Post -Headers $headers -Body $body
          Write-Output $response.Content

        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
