name: Create JIRA Ticket

on:
  push:
    branches: [master]
   
  pull_request:
    branches: [master]
jobs:
  create-jira-ticket:
    runs-on: ubuntu-latest  # Replace with your desired runner

    steps:
      - uses: actions/checkout@v4  # Checkout your code from GitHub
        with:
         node-version: '20'  # Or a later supported version
      - uses: actions/checkout@v4  # Checkout your code from GitHub
        with:
          jiraUrl: 'https://rkppersonal.atlassian.net/jira/core/projects/NEW/board'  # Replace with your JIRA URL
          apiToken: ${{ secrets.MYJIRATOKEN }}
          email: ${{ secrets.JIRA_EMAIL }}
      - name: Create JIRA ticket
        uses: atlassian/gajira-create@v3
        with:
          project: 'NewProject' # Replace with your project key
          issuetype: 'Task'  # Replace with the desired issue type
          summary: "Issue created from GitHub Actions workflow"
          description: "This ticket was automatically created by a GitHub Actions workflow."
          fields: '{"customfield_10000": "Some custom field value"}'  # Optional, replace with your custom field and value
