name: Create Jira Ticket on Commit

on:
  push:
    branches: [ master ]  # Adjust branch(es) to trigger workflow
  pull_request:
    branches: [master]
jobs:
   create-jira-ticket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create JIRA ticket
        env:
          JIRA_API_TOKEN: ${{ secrets.MYJIRATOKEN }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
        run: |
          curl -X POST \
            -H "Authorization: Basic $JIRA_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
                  "fields": {
                    "project": {
                      "key": "NewProject"
                    },
                    "summary": "Automated JIRA ticket created by GitHub Actions",
                    "description": "This JIRA ticket is automatically created based on a commit in GitHub.",
                    "issuetype": {
                      "name": "Task"  # Adjust this based on your JIRA issue type
                    },
                    "reporter": {
                      "name": "${JIRA_EMAIL}"
                    }
                  }
                }' \
            https://rkppersonal.atlassian.net/rest/api/3/issue/

